### ISSUE TITLE
RockyLinux is not supported

### ISSUE THREAD

**Issue by sandynomad** [trlinkin/puppet-nsswitch#39]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Rocky is not a supported operating system. (file: /etc/puppetlabs/code/environments/production/modules/nsswitch/manifests/params.pp, line: 194, column: 7) on node XXXXX

**Comment by jacraig-vcu** [comment]
Submitted PR #40 , which resolves this in our environment.

**Comment by delinuxspecialist** [comment]
Please merge this commit, we are using this module and need to get it running on Rocky Linux

**Comment by hboetes** [comment]
Yes, please commit this trivial PR

**Comment by hboetes** [comment]
🥳
